/* 
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Terapi.Client.Client;
using Terapi.Client.Model;

namespace Terapi.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAuthApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 23_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>GetAuthenticationTokenResponse</returns>
        GetAuthenticationTokenResponse AuthAuthenticatePost (string secretKey = null);

        /// <summary>
        /// 23_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>ApiResponse of GetAuthenticationTokenResponse</returns>
        ApiResponse<GetAuthenticationTokenResponse> AuthAuthenticatePostWithHttpInfo (string secretKey = null);
        /// <summary>
        /// 23_998
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>RefreshAuthenticationTokenResponse</returns>
        RefreshAuthenticationTokenResponse AuthRefreshPost (string refreshToken = null);

        /// <summary>
        /// 23_998
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>ApiResponse of RefreshAuthenticationTokenResponse</returns>
        ApiResponse<RefreshAuthenticationTokenResponse> AuthRefreshPostWithHttpInfo (string refreshToken = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 23_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>Task of GetAuthenticationTokenResponse</returns>
        System.Threading.Tasks.Task<GetAuthenticationTokenResponse> AuthAuthenticatePostAsync (string secretKey = null);

        /// <summary>
        /// 23_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>Task of ApiResponse (GetAuthenticationTokenResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAuthenticationTokenResponse>> AuthAuthenticatePostAsyncWithHttpInfo (string secretKey = null);
        /// <summary>
        /// 23_998
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>Task of RefreshAuthenticationTokenResponse</returns>
        System.Threading.Tasks.Task<RefreshAuthenticationTokenResponse> AuthRefreshPostAsync (string refreshToken = null);

        /// <summary>
        /// 23_998
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>Task of ApiResponse (RefreshAuthenticationTokenResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RefreshAuthenticationTokenResponse>> AuthRefreshPostAsyncWithHttpInfo (string refreshToken = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AuthApi : IAuthApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// </summary>
        /// <returns></returns>
        public AuthApi()
        {
            this.Configuration = Client.Configuration.Default;

            ExceptionFactory = Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// 23_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>GetAuthenticationTokenResponse</returns>
        public GetAuthenticationTokenResponse AuthAuthenticatePost (string secretKey = null)
        {
             ApiResponse<GetAuthenticationTokenResponse> localVarResponse = AuthAuthenticatePostWithHttpInfo(secretKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 23_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>ApiResponse of GetAuthenticationTokenResponse</returns>
        public ApiResponse< GetAuthenticationTokenResponse > AuthAuthenticatePostWithHttpInfo (string secretKey = null)
        {

            var localVarPath = "/auth/authenticate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (secretKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "SecretKey", secretKey)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("AuthAuthenticatePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetAuthenticationTokenResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetAuthenticationTokenResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetAuthenticationTokenResponse)));
        }

        /// <summary>
        /// 23_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>Task of GetAuthenticationTokenResponse</returns>
        public async System.Threading.Tasks.Task<GetAuthenticationTokenResponse> AuthAuthenticatePostAsync (string secretKey = null)
        {
             ApiResponse<GetAuthenticationTokenResponse> localVarResponse = await AuthAuthenticatePostAsyncWithHttpInfo(secretKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 23_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_999_101 | UnknownExceptionWhenTryingFetchApplicationApiKey |  |  | 23_999_102 | FailedToFindApplicationApiKey |  |  | 23_999_103 | UnknownExceptionWhenTryingToGetUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="secretKey"> (optional)</param>
        /// <returns>Task of ApiResponse (GetAuthenticationTokenResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetAuthenticationTokenResponse>> AuthAuthenticatePostAsyncWithHttpInfo (string secretKey = null)
        {

            var localVarPath = "/auth/authenticate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (secretKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "SecretKey", secretKey)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("AuthAuthenticatePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetAuthenticationTokenResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetAuthenticationTokenResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetAuthenticationTokenResponse)));
        }

        /// <summary>
        /// 23_998 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>RefreshAuthenticationTokenResponse</returns>
        public RefreshAuthenticationTokenResponse AuthRefreshPost (string refreshToken = null)
        {
             ApiResponse<RefreshAuthenticationTokenResponse> localVarResponse = AuthRefreshPostWithHttpInfo(refreshToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 23_998 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>ApiResponse of RefreshAuthenticationTokenResponse</returns>
        public ApiResponse< RefreshAuthenticationTokenResponse > AuthRefreshPostWithHttpInfo (string refreshToken = null)
        {

            var localVarPath = "/auth/refresh";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (refreshToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "RefreshToken", refreshToken)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("AuthRefreshPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RefreshAuthenticationTokenResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RefreshAuthenticationTokenResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RefreshAuthenticationTokenResponse)));
        }

        /// <summary>
        /// 23_998 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>Task of RefreshAuthenticationTokenResponse</returns>
        public async System.Threading.Tasks.Task<RefreshAuthenticationTokenResponse> AuthRefreshPostAsync (string refreshToken = null)
        {
             ApiResponse<RefreshAuthenticationTokenResponse> localVarResponse = await AuthRefreshPostAsyncWithHttpInfo(refreshToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 23_998 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 23_998_101 | UnknownExceptionWhenTryingToRefreshUserAuthenticationToken |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshToken"> (optional)</param>
        /// <returns>Task of ApiResponse (RefreshAuthenticationTokenResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RefreshAuthenticationTokenResponse>> AuthRefreshPostAsyncWithHttpInfo (string refreshToken = null)
        {

            var localVarPath = "/auth/refresh";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (refreshToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "RefreshToken", refreshToken)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("AuthRefreshPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RefreshAuthenticationTokenResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RefreshAuthenticationTokenResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RefreshAuthenticationTokenResponse)));
        }

    }
}
