/* 
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Terapi.Client.Client;
using Terapi.Client.Model;

namespace Terapi.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IIntegrationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 17_997
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>GetOneIntegrationResponse</returns>
        GetOneIntegrationResponse IntegrationGetGet (Guid? id = null);

        /// <summary>
        /// 17_997
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>ApiResponse of GetOneIntegrationResponse</returns>
        ApiResponse<GetOneIntegrationResponse> IntegrationGetGetWithHttpInfo (Guid? id = null);
        /// <summary>
        /// 17_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>IntegrationListResponse</returns>
        IntegrationListResponse IntegrationListGet (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null);

        /// <summary>
        /// 17_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>ApiResponse of IntegrationListResponse</returns>
        ApiResponse<IntegrationListResponse> IntegrationListGetWithHttpInfo (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 17_997
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of GetOneIntegrationResponse</returns>
        System.Threading.Tasks.Task<GetOneIntegrationResponse> IntegrationGetGetAsync (Guid? id = null);

        /// <summary>
        /// 17_997
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of ApiResponse (GetOneIntegrationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetOneIntegrationResponse>> IntegrationGetGetAsyncWithHttpInfo (Guid? id = null);
        /// <summary>
        /// 17_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>Task of IntegrationListResponse</returns>
        System.Threading.Tasks.Task<IntegrationListResponse> IntegrationListGetAsync (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null);

        /// <summary>
        /// 17_999
        /// </summary>
        /// <remarks>
        /// ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>Task of ApiResponse (IntegrationListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IntegrationListResponse>> IntegrationListGetAsyncWithHttpInfo (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class IntegrationApi : IIntegrationApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IntegrationApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationApi"/> class
        /// </summary>
        /// <returns></returns>
        public IntegrationApi()
        {
            this.Configuration = Client.Configuration.Default;

            ExceptionFactory = Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public IntegrationApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// 17_997 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>GetOneIntegrationResponse</returns>
        public GetOneIntegrationResponse IntegrationGetGet (Guid? id = null)
        {
             ApiResponse<GetOneIntegrationResponse> localVarResponse = IntegrationGetGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 17_997 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>ApiResponse of GetOneIntegrationResponse</returns>
        public ApiResponse< GetOneIntegrationResponse > IntegrationGetGetWithHttpInfo (Guid? id = null)
        {

            var localVarPath = "/integration/get";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Id", id)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("IntegrationGetGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetOneIntegrationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetOneIntegrationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetOneIntegrationResponse)));
        }

        /// <summary>
        /// 17_997 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of GetOneIntegrationResponse</returns>
        public async System.Threading.Tasks.Task<GetOneIntegrationResponse> IntegrationGetGetAsync (Guid? id = null)
        {
             ApiResponse<GetOneIntegrationResponse> localVarResponse = await IntegrationGetGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 17_997 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of ApiResponse (GetOneIntegrationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetOneIntegrationResponse>> IntegrationGetGetAsyncWithHttpInfo (Guid? id = null)
        {

            var localVarPath = "/integration/get";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Id", id)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("IntegrationGetGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetOneIntegrationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetOneIntegrationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetOneIntegrationResponse)));
        }

        /// <summary>
        /// 17_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>IntegrationListResponse</returns>
        public IntegrationListResponse IntegrationListGet (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null)
        {
             ApiResponse<IntegrationListResponse> localVarResponse = IntegrationListGetWithHttpInfo(page, perPage, searchKeyword, categoryId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 17_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>ApiResponse of IntegrationListResponse</returns>
        public ApiResponse< IntegrationListResponse > IntegrationListGetWithHttpInfo (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null)
        {

            var localVarPath = "/integration/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Page", page)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "PerPage", perPage)); // query parameter
            if (searchKeyword != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchKeyword", searchKeyword)); // query parameter
            if (categoryId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "CategoryId", categoryId)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("IntegrationListGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IntegrationListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IntegrationListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IntegrationListResponse)));
        }

        /// <summary>
        /// 17_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>Task of IntegrationListResponse</returns>
        public async System.Threading.Tasks.Task<IntegrationListResponse> IntegrationListGetAsync (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null)
        {
             ApiResponse<IntegrationListResponse> localVarResponse = await IntegrationListGetAsyncWithHttpInfo(page, perPage, searchKeyword, categoryId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 17_999 ### Error Codes  | Code | Name | Message |  | :- -- | :- -- | :- -- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="searchKeyword"> (optional)</param>
        /// <param name="categoryId"> (optional)</param>
        /// <returns>Task of ApiResponse (IntegrationListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<IntegrationListResponse>> IntegrationListGetAsyncWithHttpInfo (int? page = null, int? perPage = null, string searchKeyword = null, Guid? categoryId = null)
        {

            var localVarPath = "/integration/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Page", page)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "PerPage", perPage)); // query parameter
            if (searchKeyword != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchKeyword", searchKeyword)); // query parameter
            if (categoryId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "CategoryId", categoryId)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("IntegrationListGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IntegrationListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IntegrationListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IntegrationListResponse)));
        }

    }
}
